# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 京东萌宠

on:
    workflow_dispatch:
    schedule:
        - cron: "40 4,10,23 * * *"
    watch:
        types: [started]
    repository_dispatch:
        types: jd_pet

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            JD_COOKIE: ${{ secrets.JD_COOKIE }}
        steps:
            - uses: actions/checkout@v2
            # 使用node12
            - name: Use Node.js 12.x
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x
            - name: npm install
              run: |
                  npm install
            - name: '运行 【京东萌宠】'
              if: env.JD_COOKIE
              run: |
                  node jd_pet.js
              env:
                  PUSH_KEY: ${{ secrets.PUSH_KEY }}
                  BARK_PUSH: ${{ secrets.BARK_PUSH }}
                  TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
                  TG_USER_ID: ${{ secrets.TG_USER_ID }}
                  BARK_SOUND: ${{ secrets.BARK_SOUND }}
                  DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
                  DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
