name: 更新互助码

on:
  workflow_dispatch:
  schedule:
     - cron: '30 4 1,10,20 * *'
  watch:
    types: started

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: 【执行更新互助码】
      run: go run -v ./...
      env:
        JD_COOKIE: ${{ secrets.JD_COOKIE }}
        JD_DEBUG: ${{ secrets.JD_DEBUG }}
        PUSH_KEY: ${{ secrets.PUSH_KEY }}
        BARK_PUSH: ${{ secrets.BARK_PUSH }}
        BARK_SOUND: ${{ secrets.BARK_SOUND }}
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        TG_USER_ID: ${{ secrets.TG_USER_ID }}
        DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
        DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
        MARKET_COIN_TO_BEANS: ${{ secrets.MARKET_COIN_TO_BEANS }}
        MARKET_REWARD_NOTIFY: ${{ secrets.MARKET_REWARD_NOTIFY }}
